### ISSUE TITLE
F401 handling trips on star imports

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter-flake8#104]
```py
from .disable_all import *
```

```
SublimeLinter: #1507 linter.py:1263   Running ...

  /home/fichte/.config/sublime-text-3/Packages/Troubleshooting  (working dir)
  $ cat commands/__init__.py | /usr/bin/flake8 --format default --max-line-length=99 --ignore=E201,E221,E222,E241,W191,W2,W503,D1,D211,D413,D -

SublimeLinter: #1507 linter.py:955    flake8: output:
  stdin:1:1: F403 'from .disable_all import *' used; unable to detect undefined names
  stdin:1:1: F401 '.disable_all.*' imported but unused
SublimeLinter: #1507 __init__.py:1273 ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 111, in execute_lint_task
    errors = linter.lint(code, view_has_changed) or []
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 924, in lint
    return self.parse_output(output, virtual_view)
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter-flake8.sublime-package/linter.py", line 64, in parse_output
    errors = super().parse_output(proc, virtual_view)
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 945, in parse_output
    return self.parse_output_via_regex(output, virtual_view)
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 966, in parse_output_via_regex
    error = self.process_match(m, virtual_view)
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1050, in process_match
    line, start, end = self.reposition_match(m.line, col, m, vv)
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter-flake8.sublime-package/linter.py", line 145, in reposition_match
    pattern = re.compile(r'\b({})\b'.format(import_id))
  File "./python3.3/re.py", line 214, in compile
  File "./python3.3/re.py", line 283, in _compile
  File "./python3.3/sre_compile.py", line 491, in compile
  File "./python3.3/sre_parse.py", line 747, in parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 695, in _parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 568, in _parse
sre_constants.error: nothing to repeat
```

**Comment by kaste** [comment]
re.escape for the win?

**Comment by kaste** [comment]
🤞 and thanks for reporting. Now we know that nobody uses star imports anymore.

**Comment by FichteFoll** [comment]
Yeah going through some old-ish codebase. I do actually use them occasionally, but only for modularized ST plugins and usually have a `noqa: F401` line behind those.
