### ISSUE TITLE
flake8 Version Conflict with pep8 1.6.2 (current version)

### ISSUE THREAD

**Issue by utkonos** [SublimeLinter/SublimeLinter-flake8#27]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 34, in plugin_loaded
    linter.initialize()
  File "linter in /Users/username/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flake8.sublime-package", line 94, in initialize
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2354, in load
    self.require(_args, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pep8 1.6.2 (/usr/local/lib/python3.5/site-packages), Requirement.parse('pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7'))

**Comment by grotewold** [comment]
Does flake8, the command line tool, itself work with the new pep8 installed?

**Comment by fabianbuechler** [comment]
Yes it does.

I've got the same problem with pyflakes at the moment, but also had it with pep8 at times:

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/fabianbuechler/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 34, in plugin_loaded
    linter.initialize()
  File "linter in /Users/fabianbuechler/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flake8.sublime-package", line 94, in initialize
  File "/Users/fabianbuechler/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/Users/fabianbuechler/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/fabianbuechler/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pyflakes 1.0.0 (/Users/fabianbuechler/.pyenv/versions/3.4.3/lib/python3.4/site-packages), Requirement.parse('pyflakes<0.9,>=0.8.1'))
```

I've got these versions of flake8, pyflakes, pep8, pep257 and mccabe installed:

* flake8: 2.4.1
* mccabe: 0.3.1
* pep257: 0.6.0
* pep8: 1.6.2
* pyflakes: 1.0.0

Works without any problems when calling `flake8` directly, but the linter plugin does not work, likely due to the `pkg_resources.load` call, which checks `install_requires`. flake8 has these versions defined in its `setup.py`:

```python
    install_requires=[
        "pyflakes >= 0.8.1, < 0.9",
        "pep8 >= 1.5.7, != 1.6.0, != 1.6.1, != 1.6.2",
        "mccabe >= 0.2.1, < 0.4",
    ],
```

But since it still works when using it directly, why does the linter plugin need to do this check?

**Comment by Ap0c** [comment]
I got around this problem by downgrading pep8 to version 1.5.7, as described in [this StackOverflow post](http://stackoverflow.com/questions/29340658/flake8-2-4-0-not-support-pep8-1-6-2-version/29340700#29340700).

It seems that flake8 has [blacklisted recent versions](https://github.com/PyCQA/pep8/issues/427) of pep8.
