### ISSUE TITLE
SublimeLinter: ERROR: exception in flake8.check: 'module' object has no attribute 'builtin_vars' 

### ISSUE THREAD

**Issue by miohtama** [SublimeLinter/SublimeLinter-flake8#4]
I am just doing fresh Sublime Text 3 + SublimeLinter installation. I am getting the following:

```
reloading plugin SublimeLinter-flake8.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /Users/mikko/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flake8.sublime-package", line 17, in <module>
  File "/Users/mikko/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 124, in __init__
    cls.reinitialize()
  File "/Users/mikko/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/python_linter.py", line 98, in reinitialize
    cls.initialize()
  File "linter in /Users/mikko/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flake8.sublime-package", line 53, in initialize
SystemError: super(): empty __class__ cell
```

Any idea what could cause this or how to start to diagnose the problem?

**Comment by groteworld** [comment]
closing due to age and rewrite of SL-flake8
