### ISSUE TITLE
AttributeError: 'module' object has no attribute 'find_python'

### ISSUE THREAD

**Issue by cixtor** [SublimeLinter/SublimeLinter-flake8#80]
```
Traceback (most recent call last):
  File "/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/SublimeLinter-flake8/util.py", line 175, in <module>
    find_python = util.find_python

AttributeError: 'module' object has no attribute 'find_python'
```

**Comment by kaste** [comment]
You need to install the beta flake8 plugin for SL4 beta.

**Comment by jmagnusson** [comment]
@kaste Why is that? SublimeLinter-flake8 just stopped working a few days ago because of this error.

**Comment by kaste** [comment]
Do you get same exact error? Do you have SL4?
