### ISSUE TITLE
AttributeError: 'Flake8' object has no attribute 'get_chdir'

### ISSUE THREAD

**Issue by cixtor** [SublimeLinter/SublimeLinter-flake8#81]
```
Traceback (most recent call last):
  File "/SublimeLinter/lint/backend.py", line 201, in await_futures
    yield future.result()
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/SublimeLinter/lint/backend.py", line 96, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/SublimeLinter/lint/linter.py", line 908, in lint
    cmd = self.get_cmd()
  File "/SublimeLinter/lint/linter.py", line 631, in get_cmd
    return self.build_cmd(cmd)
  File "/SublimeLinter/lint/linter.py", line 644, in build_cmd
    have_path, path = self.context_sensitive_executable_path(cmd)
  File "/SublimeLinter-flake8/linter.py", line 145, in context_sensitive_executable_path
    chdir = self.get_chdir(settings)

AttributeError: 'Flake8' object has no attribute 'get_chdir'
```

**Comment by kaste** [comment]
You need to install the beta flake8 plugin for SL4 beta.
