### ISSUE TITLE
Linter crashed: Bad file descriptor

### ISSUE THREAD

**Issue by Mattiaslndstrm** [SublimeLinter/SublimeLinter-flake8#87]
Not really a problem since it restarted right after, but I thought you might want the traceback:

```SublimeLinter: #475 flake8 untitled5.py ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 797, in lint
  File "lint.linter in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1145, in run
  File "lint.linter in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1194, in communicate
  File "lint.util in /Users/Mattias/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 225, in communicate
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1556, in _communicate
  File "./python3.3/subprocess.py", line 1670, in _communicate_with_poll
  File "./python3.3/subprocess.py", line 1607, in close_unregister_and_remove
OSError: [Errno 9] Bad file descriptor```

**Comment by Mattiaslndstrm** [comment]
No worries! Not sure if this is any help, but it always seems to happen when I'm building some code.

**Comment by kaste** [comment]
We catch and handle `Bad File Descriptor` errors in SL core land, probably since a few months now. So this should be fixed, I guess.
